version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: cargo_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: cargo_frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: cargo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cargo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
